# Generated by Django 4.2.11 on 2024-04-14 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='about',
            options={'ordering': ['title']},
        ),
    ]
