# Generated by Django 4.2.11 on 2024-04-14 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_alter_about_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='about',
            options={},
        ),
    ]
